### ISSUE TITLE
client: {useIframe: false} not taken from config file

### ISSUE THREAD

**Issue by ghost** [karma-runner/grunt-karma#165] opened 2015-09-23 18:44 UTC
If I want this option, I need to add it to grunt config itself.

**Comment by Dignifiedquire** [comment] 2015-09-27 17:58
Can you please describe in more detail what you are trying to achieve and what you tried and did not work for you?

**Comment by herby** [comment] 2015-09-27 18:47
I just want to use option `useIframe: false`. Ad "what you are trying to achieve", I hope you are not saying I should explain why I want to use that option - I have my reasons.

When it is specified in `.conf` file, it works fine from cli `karma`, but it is not honoured when used in `grunt-karma`. Hence, bug. As a workaround, I need to put `options: {useIframe: false}` into Gruntfile itself. Please, will you accept this bug (`useIframe` setting in `.conf` is not taken by grunt-karma)?

It is a bug, isn't it?

**Comment by Dignifiedquire** [comment] 2015-09-27 19:12
So you are saying you are setting the value in the your `karma.conf.js` file, and when running it via the cli it works fine, but when running it through grunt-karma it is not honoured? Could you share how your grunt-karma config looks like then please?

**Comment by herby** [comment] 2015-09-27 19:32
It is pointing to that config file, but useIframe is not honoured. Other settings are.

Friedel Ziegelmayer wrote:

**Comment by herby** [comment] 2015-10-02 13:08
The problem seems to be here: https://github.com/karma-runner/grunt-karma/blob/70cdb9416716a7e228971508fe5f683a4a53c5fd/tasks/grunt-karma.js#L40-L56.
Since I do not run `grunt`, but `grunt taskname`, the client is set to `{}`, then gets the defaults applied, setting `useIframe` always to `true`, and all this before taking configfile into account.

**Comment by herby** [comment] 2015-10-02 13:19
No, in fact, this is the root cause: https://github.com/karma-runner/grunt-karma/blob/70cdb9416716a7e228971508fe5f683a4a53c5fd/tasks/grunt-karma.js#L31.

**Comment by herby** [comment] 2015-10-02 14:42
Or maybe this https://github.com/karma-runner/grunt-karma/commit/168f7b7a6af02e78e44b87b27553cdb65785221c. Why was useIframe: true set as default explicitly; is it needed?

**Comment by herby** [comment] 2015-10-02 14:46
Re: "PR please" @Dignifiedquire I am not really sure how to solve this, as there is many places and they depend on each other, so you could probably know better (or some other core devs).

**Comment by gnail** [comment] 2016-06-28 20:10
Can confirm that [the default settings](https://github.com/karma-runner/grunt-karma/blob/master/tasks/grunt-karma.js#L53) overrides the config file and sets UseIframe to true regardless of the config file. I ran into this while trying to get [karma-electron](https://github.com/twolfson/karma-electron) to work which requires UseIframe to be false in order to expose the Node.js API visible from the renderer. Removing line 53 solves my problem.

**Comment by ianwremmel** [comment] 2016-06-29 00:04
Seeing the same problem. 

https://github.com/karma-runner/grunt-karma/blob/70cdb9416716a7e228971508fe5f683a4a53c5fd/tasks/grunt-karma.js#L31 ensures that any client configuration provided in the karma config file gets discarded.

**Comment by ianwremmel** [comment] 2016-06-29 00:06
@gnail , I'm not sure your PR entirely fixes the problem. I think the presence of options.client always means that the client provided in the config file will get discarded.

**Comment by gnail** [comment] 2016-06-29 02:55
@ianwremmel Hmm I could've sworn that it fixed my issue but revisiting the issue says otherwise. My apologies. I think the issue lies in [Karma](https://github.com/karma-runner/karma/blob/master/lib/config.js#L228) where sub-properties are overwritten instead of merged. My PR solves half of the issue since hard-coded properties like that would take precedence no matter what, but it'd take another PR on Karma itself to solve this fully.

We could remove the empty client object too and clean up the code a bit but that'd still leave cases where passing in args or a single property overrides other properties specified in the config file.

**Comment by gnail** [comment] 2016-06-29 03:19
I've created another PR for Karma itself. Both of these PRs work together to solve this and related issues.

**Closed** 2016-07-11 11:02 UTC
Labels: PR please, type: bug
